runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /static/images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)
- url: /.*
  static_files: www/home.html
  upload: www/(.*)
  secure: always
  redirect_http_response_code: 301
